import re

replacements = {
    r'\bGestion\b': 'Gestión',
    r'\bgestion\b': 'gestión',
    r'\bIntroduccion\b': 'Introducción',
    r'\bindice\b': 'índice',
    r'\bIndice\b': 'Índice',
    r'\bPagina\b': 'Página',
    r'\bpagina\b': 'página',
    r'\baplicacion\b': 'aplicación',
    r'\bmovil\b': 'móvil',
    r'\btecnica\b': 'técnica',
    r'\bevaluacion\b': 'evaluación',
    r'\btambien\b': 'también',
    r'\bhabitacion\b': 'habitación',
    r'\bhabitaciones\b': 'habitaciones', # correct already, but for safety
    r'\bestetica\b': 'estética',
    r'\bdecision\b': 'decisión',
    r'\bpractico\b': 'práctico',
    r'\badministracion\b': 'administración',
    r'\boptima\b': 'óptima',
    r'\baplicandose\b': 'aplicándose',
    r'\bfilosofia\b': 'filosofía',
    r'\bcaracteristicas\b': 'características',
    r'\bdomotica\b': 'domótica',
    r'\bestan\b': 'están',
    r'\bmayoria\b': 'mayoría',
    r'\bpoblacion\b': 'población',
    r'\bper capita\b': 'per cápita',
    r'\btecnologica\b': 'tecnológica',
    r'\btecnologico\b': 'tecnológico',
    r'\bbasico\b': 'básico',
    r'\bbasica\b': 'básica',
    r'\bnotificacion\b': 'notificación',
    r'\basi\b': 'así',
    r'\bobservacion\b': 'observación',
    r'\bempirica\b': 'empírica',
    r'\brecoleccion\b': 'recolección',
    r'\brealizo\b': 'realizó',
    r'\btraves\b': 'través',
    r'\bsesion\b': 'sesión',
    r'\bconfusion\b': 'confusión',
    r'\bsatisfaccion\b': 'satisfacción',
    r'\bseleccion\b': 'selección',
    r'\barea\b': 'área',
    r'\bcodigo\b': 'código',
    r'\binformacion\b': 'información',
    r'\borganizacion\b': 'organización',
    r'\bjustificacion\b': 'justificación',
    r'\bespecifica\b': 'específica',
    r'\baccion\b': 'acción',
    r'\bcreacion\b': 'creación',
    r'\bcategorizacion\b': 'categorización',
    r'\bagrupacion\b': 'agrupación',
    r'\bincorporacion\b': 'incorporación',
    r'\bdiferenciacion\b': 'diferenciación',
    r'\btecnologia\b': 'tecnología',
    r'\bCuantos\b': 'Cuántos',
    r'\bCuales\b': 'Cuáles',
    r'\bconfiguracion\b': 'configuración',
    r'\bEjecucion\b': 'Ejecución',
    r'\belectrodomestico\b': 'electrodoméstico',
    r'\bocurrio\b': 'ocurrió',
    r'\bprendi\b': 'prendí',
    r'\bapague\b': 'apagué',
    r'\bhabitos\b': 'hábitos',
    r'\bautomatizacion\b': 'automatización',
    r'\brelacion\b': 'relación',
    r'\belectronicos\b': 'electrónicos',
    r'\bfisica\b': 'física',
    r'\bseria\b': 'sería',
    r'\bDefinicion\b': 'Definición',
    r'\binteractua\b': 'interactúa',
    r'\badopcion\b': 'adopción',
    r'\bnavegacion\b': 'navegación',
    r'\binversion\b': 'inversión',
    r'\bvalidara\b': 'validará',
    r'\bOcupacion\b': 'Ocupación',
    r'\bUbicacion\b': 'Ubicación',
    r'\bhare\b': 'haré',
    r'\bCentralizacion\b': 'Centralización',
    r'\bAnalisis\b': 'Análisis',
    r'\bconfirmacion\b': 'confirmación',
    r'\bseccion\b': 'sección',
    r'\bcalido\b': 'cálido',
    r'\benergetico\b': 'energético',
    r'\bfaciles\b': 'fáciles',
    r'\bingreso\b': 'ingresó',
    r'\bdesactivo\b': 'desactivó',
    r'\bpronostico\b': 'pronóstico',
    r'\binstalo\b': 'instaló',
    r'\bavion\b': 'avión',
    r'\bFisica\b': 'Física',
    r'\bAutonomia\b': 'Autonomía',
    r'\bVerificacion\b': 'Verificación',
    r'\bmetodologia\b': 'metodología',
    r'\binspeccion\b': 'inspección',
    r'\bcomun\b': 'común',
    r'\bcritico\b': 'crítico',
    r'\bcosmetico\b': 'cosmético',
    r'\bHeuristica\b': 'Heurística',
    r'\bejecuto\b': 'ejecutó',
    r'\bPrevencion\b': 'Prevención',
    r'\btendria\b': 'tendría',
    r'\brevision\b': 'revisión',
    r'\btipografica\b': 'tipográfica',
    r'\bunica\b': 'única',
    r'\bimplementacion\b': 'implementación',
    r'\borientacion\b': 'orientación',
    r'\bAccion\b': 'Acción',
    r'\bencontro\b': 'encontró',
    r'\bdesaparecia\b': 'desaparecía',
    r'\badopto\b': 'adoptó',
    r'\breorganizo\b': 'reorganizó',
    r'\btitulos\b': 'títulos',
    r'\bdistribucion\b': 'distribución',
    r'\btermino\b': 'término',
    r'\brenombro\b': 'renombró',
    r'\bAdaptacion\b': 'Adaptación',
    r'\binteraccion\b': 'interacción',
    r'\biteracion\b': 'iteración',
    r'\bhexagono\b': 'hexágono',
    r'\bsensacion\b': 'sensación',
    r'\bambar\b': 'ámbar',
    r'\bhogarenos\b': 'hogareños',
    r'\bestandar\b': 'estándar',
    r'\btipografia\b': 'tipografía',
    r'\biconografia\b': 'iconografía',
    r'\blinea\b': 'línea',
    r'\binstantaneas\b': 'instantáneas',
    r'\blexica\b': 'léxica',
    r'\blampara\b': 'lámpara',
    r'\batras\b': 'atrás',
    r'\brendio\b': 'rendió',
    r'\bmas\b': 'más',
    r'\bsi\b': 'sí',
    r'\bCuando\b': 'Cuándo',
    r'\bQue\b': 'Qué',
    r'\bCual\b': 'Cuál',
}

with open('/Users/juaniraggio/workspace/itbaworkspace/3_ro/HCInteraction/HomeCore/docs/informe.typ', 'r') as f:
    content = f.read()

# Separate content into parts to avoid replacing in paths and commands
# This is a bit complex, so I'll try a simpler approach first:
# Only replace if not preceded by # and not part of a path.
# Actually, the words I'm replacing are mostly Spanish words that won't be in Typst commands or English paths.
# "assets/image..." or "assets/personas/..." don't have these words.

def replace_all(text):
    for pattern, replacement in replacements.items():
        # Avoid replacing if it looks like a path (no slash before or after in a way that suggests a path)
        # and not inside a string like "assets/..."
        # But wait, \b pattern \b already handles word boundaries.
        text = re.sub(pattern, replacement, text)
    return text

new_content = replace_all(content)

# Special cases for "mas" and "si" where they might be used correctly without tilde
# but in this document they are mostly used with tilde.
# I'll check "mas de" -> "más de"
# "si/no" -> "sí/no"

with open('/Users/juaniraggio/workspace/itbaworkspace/3_ro/HCInteraction/HomeCore/docs/informe.typ', 'w') as f:
    f.write(new_content)
